[package]
name = "crawler"
version = "0.1.0"
authors = ["Guilherme Faustino <contato@guilhermeluis.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.12.0"
selectors = "0.22.0"